---
title: "DiOC6 & MitoSox Staining 48 hr"
author: "Burton"
date: "10/21/2020"
output: pdf_document
---
```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(stats)
library(broom)
library(kableExtra)
```

```{r}
fitcHuh <- read_tsv("tables_flowjo/48hr_dioc_Huh7.txt")
fitcVero <- read_tsv("tables_flowjo/48hr_dioc_Vero.txt")
peHuh <- read_tsv("tables_flowjo/48hr_mitosox_Huh7.txt")
peVero <- read_tsv("tables_flowjo/48hr_mitosox_Vero.txt")
```

```{r}
fitcCleanedHuh <- fitcHuh %>% 
  slice(-(7:8)) %>% 
  mutate(`Sample:` = str_replace(`Sample:`, 
                                 "DIOC 48 hr Vero and HuH7 Covid_9-10-2020_", 
                                 ""),
         `Sample:` = str_replace(`Sample:`, "_1,3a,", "_"),
         `Sample:` = str_replace(`Sample:`, ".fcs", ""),
         `Sample:` = str_replace(`Sample:`, "_[0-9][0-9][0-9]", ""),
         `Sample:` = str_replace(`Sample:`, "_[0-9][0-9][0-9]", "")) %>% 
  rename(Sample = `Sample:`,
         FITC_pos_of_singlets = `Singlets/FITC-A+ | Freq. of Parent`)

fitcCleanedVero <- fitcVero %>% 
  slice(-(10:11)) %>% 
  mutate(`Sample:` = str_replace(`Sample:`, 
                                 "DIOC 48 hr Vero and HuH7 Covid_9-10-2020_", 
                                 ""),
         `Sample:` = str_replace(`Sample:`, "_1,3a,", "_"),
         `Sample:` = str_replace(`Sample:`, ".fcs", ""),
         `Sample:` = str_replace(`Sample:`, "_[0-9][0-9][0-9]", ""),
         `Sample:` = str_replace(`Sample:`, "_[0-9][0-9][0-9]", "")) %>% 
  rename(Sample = `Sample:`,
         FITC_pos_of_singlets = `Singlets/FITC-A+ | Freq. of Parent`)


peCleanedVero <- peVero %>%
  slice(-(10:11)) %>% 
  mutate(
    `Sample:` = str_replace(`Sample:`, "MitoSoX 48 hr", ""),
    `Sample:` = str_remove(`Sample:`, "Vero and Huh7 9_10_2020_"),
    `Sample:` = str_replace(`Sample:`, "1,3a,", "_"),
    `Sample:` = str_replace(`Sample:`, ".fcs", ""),
    `Sample:` = str_replace(`Sample:`, "_[0-9][0-9][0-9]", ""),
    `Sample:` = str_replace(`Sample:`, "_[0-9][0-9][0-9]", "")) %>% 
  rename(Sample = `Sample:`,
         PE_pos_of_singlets = `Singlets/PE_pos | Freq. of Parent`)

peCleanedHuh <- peHuh %>%
  slice(-(10:11)) %>% 
  mutate(
    `Sample:` = str_replace(`Sample:`, "MitoSoX 48 hr", ""),
    `Sample:` = str_remove(`Sample:`, "Vero and Huh7 9_10_2020_"),
    `Sample:` = str_replace(`Sample:`, "1,3a,", "_"),
    `Sample:` = str_replace(`Sample:`, ".fcs", ""),
    `Sample:` = str_replace(`Sample:`, "_[0-9][0-9][0-9]", ""),
    `Sample:` = str_replace(`Sample:`, "_[0-9][0-9][0-9]", "")) %>% 
  rename(Sample = `Sample:`,
         PE_pos_of_singlets = `Singlets/PE_pos | Freq. of Parent`)
 
```

```{r}
fitcCleanedHuhGraph <- fitcCleanedHuh %>% 
  ggplot(aes(y = FITC_pos_of_singlets, x = Sample)) +
  geom_point(color = 'red') +
  theme(axis.text.x=element_text(angle=45, hjust=1))

fitcCleanedVeroGraph <- fitcCleanedVero %>% 
  ggplot(aes(y = FITC_pos_of_singlets, x = Sample)) +
  geom_point(color = 'blue') +
  theme(axis.text.x=element_text(angle=45, hjust=1))

peCleanedHuhGraph <- peCleanedHuh %>% 
  ggplot(aes(y = PE_pos_of_singlets, x = Sample)) +
  geom_point(color = 'red') +
  theme(axis.text.x=element_text(angle=45, hjust=1))

peCleanedVeroGraph <- peCleanedVero %>% 
  ggplot(aes(y = PE_pos_of_singlets, x = Sample)) +
  geom_point(color = 'blue') +
  theme(axis.text.x=element_text(angle=45, hjust=1))


gridExtra::grid.arrange(fitcCleanedHuhGraph, fitcCleanedVeroGraph, peCleanedHuhGraph, peCleanedVeroGraph)  
```

Statistics ANOVA-TukeyHSD
```{r}
fitcCleanedVero %>% 
  slice(-1) %>% 
  nest() %>%
  mutate(aov_result = map(data, ~aov(FITC_pos_of_singlets ~ Sample, data = .x)),
            tukey_result = map(aov_result, TukeyHSD),
            tidy_tukey = map(tukey_result, tidy)) %>%
     unnest(tidy_tukey, .drop = TRUE) %>% 
  select(-(1:3)) %>% 
  kable(caption="DiOC Vero")

fitcCleanedHuh %>% 
  slice(-1) %>% 
  nest() %>%
  mutate(aov_result = map(data, ~aov(FITC_pos_of_singlets ~ Sample, data = .x)),
            tukey_result = map(aov_result, TukeyHSD),
            tidy_tukey = map(tukey_result, tidy)) %>%
     unnest(tidy_tukey, .drop = TRUE) %>% 
  select(-(1:3)) %>% 
  kable(caption="DiOC Huh")

peCleanedVero %>% 
  slice(-7) %>% 
  nest() %>%
  mutate(aov_result = map(data, ~aov(PE_pos_of_singlets ~ Sample, data = .x)),
            tukey_result = map(aov_result, TukeyHSD),
            tidy_tukey = map(tukey_result, tidy)) %>%
     unnest(tidy_tukey, .drop = TRUE) %>% 
  select(-(1:3)) %>% 
  kable(caption="Mito Vero")

peCleanedHuh %>% 
  slice(-7) %>% 
  nest() %>%
  mutate(aov_result = map(data, ~aov(PE_pos_of_singlets ~ Sample, data = .x)),
            tukey_result = map(aov_result, TukeyHSD),
            tidy_tukey = map(tukey_result, tidy)) %>%
     unnest(tidy_tukey, .drop = TRUE) %>% 
  select(-(1:3)) %>% 
  kable(caption="Mito Huh")
```


