---
title: "DiOC6 & MitoSox Staining 24 hr"
author: "Burton"
date: "10/22/2020"
output: pdf_document
---
```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(stats)
library(broom)
library(kableExtra)
```

```{r}
fitcHuh <- read_tsv("tables_flowjo/24hr_dioc_huh.txt")
fitcVero <- read_tsv("tables_flowjo/24hr_dioc_vero.txt")
peHuh <- read_tsv("tables_flowjo/24hr_mito_huh.txt")
peVero <- read_tsv("tables_flowjo/24hr_mito_vero.txt")
```

```{r}
fitcCleanedHuh <- fitcHuh %>% 
  slice(-(10:11)) %>% 
  mutate(`Sample:` = str_remove(`Sample:`, "DIOC 24 hr Vero and "),
         `Sample:` = str_remove(`Sample:`, " [+],2f,- Covid_001_HuH7"),
         `Sample:` = str_remove(`Sample:`, "1,2f,"),
         `Sample:` = str_remove(`Sample:`, "_0[0-9][0-9].fcs"),
         `Sample:` = str_remove(`Sample:`, "( |_)[0-9][0-9][0-9]")) %>% 
  rename(Sample = `Sample:`,
         FITC_pos_of_singlets = `Singlets/FITC_pos | Freq. of Parent`)

fitcCleanedVero <- fitcVero %>% 
  slice(-(11:12)) %>% 
  mutate(`Sample:` = str_remove(`Sample:`, "DIOC 24 hr"),
         `Sample:` = str_remove(`Sample:`, " and HuH7 [+],2f,- Covid_001_Vero"),
         `Sample:` = str_remove(`Sample:`, "1,2f,"),
         `Sample:` = str_remove(`Sample:`, "_0[0-9][0-9].fcs"),
         `Sample:` = str_remove(`Sample:`, "_[0-9][0-9][0-9]")) %>% 
  rename(Sample = `Sample:`,
         FITC_pos_of_singlets = `Singlets/FITC_pos | Freq. of Parent`)


peCleanedVero <- peVero %>% 
  unite(PE_pos_of_singlets, 
        `Singlets/PE_pos | Freq. of Parent`:`Singlets_nossc/PE_pos | Freq. of Parent`,
        na.rm = TRUE) %>% 
  slice(-(11:12)) %>% 
  mutate(`Sample:` = str_remove(`Sample:`, "MitoSoX 24 hr "),
         `Sample:` = str_remove(`Sample:`, " and HuH7 [+],2f,- Covid_Vero"),
         `Sample:` = str_remove(`Sample:`, "1,2f,"),
         `Sample:` = str_remove(`Sample:`, "_0[0-9][0-9].fcs"),
         `Sample:` = str_remove(`Sample:`, "_[0-9][0-9][0-9]")) %>% 
  rename(Sample = `Sample:`)

peCleanedHuh <- peHuh %>% 
  slice(-(10:11)) %>% 
  mutate(`Sample:` = str_remove(`Sample:`, "MitoSoX 24 hr Vero and "),
         `Sample:` = str_remove(`Sample:`, " [+],2f,- Covid_HuH7"),
         `Sample:` = str_remove(`Sample:`, "1,2f,"),
         `Sample:` = str_remove(`Sample:`, "_0[0-9][0-9].fcs"),
         `Sample:` = str_remove(`Sample:`, "_[0-9][0-9][0-9]")) %>% 
  rename(Sample = `Sample:`,
         PE_pos_of_singlets = `Singlets/PE_pos | Freq. of Parent`)
 
```


```{r}
fitcCleanedHuhGraph <- fitcCleanedHuh %>% 
  ggplot(aes(y = FITC_pos_of_singlets, x = Sample)) +
  geom_point(color = 'red') +
  theme(axis.text.x=element_text(angle=45, hjust=1))

fitcCleanedVeroGraph <- fitcCleanedVero %>% 
  ggplot(aes(y = FITC_pos_of_singlets, x = Sample)) +
  geom_point(color = 'blue') +
  theme(axis.text.x=element_text(angle=45, hjust=1))

peCleanedHuhGraph <- peCleanedHuh %>% 
  ggplot(aes(y = PE_pos_of_singlets, x = Sample)) +
  geom_point(color = 'red') +
  theme(axis.text.x=element_text(angle=45, hjust=1))

peCleanedVeroGraph <- peCleanedVero %>% 
  ggplot(aes(y = PE_pos_of_singlets, x = Sample)) +
  geom_point(color = 'blue') +
  theme(axis.text.x=element_text(angle=45, hjust=1))


gridExtra::grid.arrange(fitcCleanedHuhGraph, fitcCleanedVeroGraph, 
                        peCleanedHuhGraph, peCleanedVeroGraph)  
```

Statistics ANOVA-TukeyHSD
```{r}
fitcCleanedVero %>% 
  slice(-1) %>% 
  nest() %>%
  mutate(aov_result = map(data, ~aov(FITC_pos_of_singlets ~ Sample, data = .x)),
            tukey_result = map(aov_result, TukeyHSD),
            tidy_tukey = map(tukey_result, tidy)) %>%
     unnest(tidy_tukey, .drop = TRUE) %>% 
  select(-(1:3)) %>% 
  kable(caption="DiOC Vero")

fitcCleanedHuh %>% 
  slice(-1) %>%  
  nest() %>%
  mutate(aov_result = map(data, ~aov(FITC_pos_of_singlets ~ Sample, data = .x)),
            tukey_result = map(aov_result, TukeyHSD),
            tidy_tukey = map(tukey_result, tidy)) %>%
     unnest(tidy_tukey, .drop = TRUE) %>% 
  select(-(1:3)) %>% 
  kable(caption="DiOC Huh")

peCleanedVero %>% 
  slice(-1) %>% 
  nest() %>%
  mutate(aov_result = map(data, ~aov(PE_pos_of_singlets ~ Sample, data = .x)),
            tukey_result = map(aov_result, TukeyHSD),
            tidy_tukey = map(tukey_result, tidy)) %>%
     unnest(tidy_tukey, .drop = TRUE) %>% 
  select(-(1:3)) %>% 
  kable(caption="Mito Vero")

peCleanedHuh %>% 
  slice(-1) %>% 
  nest() %>%
  mutate(aov_result = map(data, ~aov(PE_pos_of_singlets ~ Sample, data = .x)),
            tukey_result = map(aov_result, TukeyHSD),
            tidy_tukey = map(tukey_result, tidy)) %>%
     unnest(tidy_tukey, .drop = TRUE) %>% 
  select(-(1:3)) %>% 
  kable(caption="Mito Huh")
```


